create table if not exists endpoint_hit
(
    id        bigint generated by default as identity,
    app       varchar(255)                not null,
    uri       varchar(255)                not null,
    ip        varchar(255)                not null,
    timestamp timestamp without time zone not null,
    constraint pk_endpoint_hit primary key (id)
);