create table if not exists endpoint_hit
(
    id        bigint generated by default as identity,
    app       varchar(255)                not null,
    uri       varchar(255)                not null,
    ip        varchar(255)                not null,
    timestamp timestamp without time zone not null,
    constraint pk_endpoint_hit primary key (id)
);

create index if not exists idx_endpoint_hit_timestamp on endpoint_hit (timestamp);
create index if not exists idx_endpoint_hit_uri on endpoint_hit (uri);
create index if not exists idx_endpoint_hit_app on endpoint_hit (app);
create index if not exists idx_endpoint_hit_ip on endpoint_hit (ip);